"""phase3: article.raw_signals for trend popularity

Revision ID: 3be64b334355
Revises: ba30afb93e4f
Create Date: 2026-06-17 15:15:31.912575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be64b334355'
down_revision: Union[str, Sequence[str], None] = 'ba30afb93e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows with an empty object so the NOT NULL
    # constraint holds; the ORM always supplies a value on new inserts.
    op.add_column(
        'articles',
        sa.Column('raw_signals', sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'raw_signals')
    # ### end Alembic commands ###
