"""article processed_at + seen_hashes retention

Revision ID: ba30afb93e4f
Revises: b3bf0b4746ae
Create Date: 2026-06-17 14:45:39.127337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba30afb93e4f'
down_revision: Union[str, Sequence[str], None] = 'b3bf0b4746ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seen_hashes',
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('url_hash')
    )
    op.create_index(op.f('ix_seen_hashes_last_seen'), 'seen_hashes', ['last_seen'], unique=False)
    op.add_column('articles', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_articles_collected_at'), 'articles', ['collected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_collected_at'), table_name='articles')
    op.drop_column('articles', 'processed_at')
    op.drop_index(op.f('ix_seen_hashes_last_seen'), table_name='seen_hashes')
    op.drop_table('seen_hashes')
    # ### end Alembic commands ###
