"""Generic repository.

The repository layer is the ONLY place that touches the ORM session. Services
and API routes depend on repositories, never on SQLAlchemy directly — so storage
can change without rippling through the app.

`BaseRepository` provides the common CRUD; concrete repos subclass it and add
domain queries.
"""

from __future__ import annotations

from typing import Generic, TypeVar

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.database.session import Base

ModelT = TypeVar("ModelT", bound=Base)


class BaseRepository(Generic[ModelT]):
    """CRUD over one ORM model.

    Commits are caller-controlled by default: `create`/`update`/`delete` flush so
    autogenerated ids are available, but the surrounding service decides when to
    `commit()`. Pass `commit=True` for one-off scripts (e.g. seeding).
    """

    model: type[ModelT]

    def __init__(self, db: Session) -> None:
        self.db = db

    def get(self, id: int) -> ModelT | None:
        return self.db.get(self.model, id)

    def list(self, *, limit: int = 100, offset: int = 0) -> list[ModelT]:
        stmt = select(self.model).limit(limit).offset(offset)
        return list(self.db.execute(stmt).scalars().all())

    def create(self, obj: ModelT, *, commit: bool = False) -> ModelT:
        self.db.add(obj)
        self.db.flush()
        if commit:
            self.db.commit()
            self.db.refresh(obj)
        return obj

    def update(self, obj: ModelT, *, commit: bool = False) -> ModelT:
        self.db.add(obj)
        self.db.flush()
        if commit:
            self.db.commit()
            self.db.refresh(obj)
        return obj

    def delete(self, id: int, *, commit: bool = False) -> bool:
        obj = self.get(id)
        if obj is None:
            return False
        self.db.delete(obj)
        self.db.flush()
        if commit:
            self.db.commit()
        return True
